# Generated by Django 4.1.3 on 2022-12-01 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(blank=True, choices=[('', 'اختار المبني'), ('kg', 'رياض أطفال'), ('moaaz', 'معاذ ابن جبل'), ('abobakr', 'أبو بكر الصديق'), ('prep', 'إعدادي وثانوي'), ('american', 'الامريكية'), ('new-american', 'الامريكية الجديد'), ('administartor', 'الإدارة')], max_length=30, null=True)),
                ('stage', models.CharField(blank=True, max_length=30, null=True)),
                ('it_support', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Add_DVR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('floor', models.CharField(blank=True, max_length=30, null=True)),
                ('ips', models.CharField(blank=True, max_length=30, null=True)),
                ('ports', models.CharField(blank=True, max_length=30, null=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow.building')),
            ],
        ),
    ]
