# Generated by Django 4.1.3 on 2022-12-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='b_name',
            field=models.CharField(blank=True, choices=[('', 'اختار المبني'), ('رياض أطفال', 'رياض أطفال'), ('معاذ ابن جبل', 'معاذ ابن جبل'), ('أبو بكر الصديق', 'أبو بكر الصديق'), ('إعدادي وثانوي', 'إعدادي وثانوي'), ('الامريكية', 'الامريكية'), ('الامريكية الجديد', 'الامريكية الجديد'), ('الإدارة', 'الإدارة')], max_length=30, null=True),
        ),
    ]
