# Generated by Django 4.1.3 on 2022-12-01 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0002_alter_building_b_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.CharField(blank=True, max_length=30, null=True)),
                ('mic', models.CharField(blank=True, max_length=30, null=True)),
                ('record', models.CharField(blank=True, max_length=30, null=True)),
                ('hdd', models.CharField(blank=True, max_length=30, null=True)),
                ('power', models.CharField(blank=True, max_length=30, null=True)),
                ('lan', models.CharField(blank=True, max_length=30, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow.add_dvr')),
            ],
        ),
    ]
