# Generated by Django 4.1.3 on 2022-12-01 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0003_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='hdd',
            field=models.CharField(blank=True, choices=[('يعمل بكفائه', 'يعمل بكفائه'), ('توجد مشكلة', 'توجد مشكلة'), ('تم حل المشكلة', 'تم حل المشكلة')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='images',
            field=models.CharField(blank=True, choices=[('يعمل بكفائه', 'يعمل بكفائه'), ('توجد مشكلة', 'توجد مشكلة'), ('تم حل المشكلة', 'تم حل المشكلة')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='lan',
            field=models.CharField(blank=True, choices=[('يعمل بكفائه', 'يعمل بكفائه'), ('توجد مشكلة', 'توجد مشكلة'), ('تم حل المشكلة', 'تم حل المشكلة')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='mic',
            field=models.CharField(blank=True, choices=[('يعمل بكفائه', 'يعمل بكفائه'), ('توجد مشكلة', 'توجد مشكلة'), ('تم حل المشكلة', 'تم حل المشكلة')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='power',
            field=models.CharField(blank=True, choices=[('يعمل بكفائه', 'يعمل بكفائه'), ('توجد مشكلة', 'توجد مشكلة'), ('تم حل المشكلة', 'تم حل المشكلة')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='record',
            field=models.CharField(blank=True, choices=[('يعمل بكفائه', 'يعمل بكفائه'), ('توجد مشكلة', 'توجد مشكلة'), ('تم حل المشكلة', 'تم حل المشكلة')], max_length=30, null=True),
        ),
    ]
