# Generated by Django 3.2 on 2022-12-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0005_auto_20221203_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='notes',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
