# Generated by Django 3.2 on 2023-01-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0007_auto_20221210_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='it_support',
            field=models.CharField(blank=True, choices=[('', 'المهندس المسؤل'), ('م. تامر خير', 'م. تامر خير'), ('م. محمد جمال', 'م. محمد جمال'), ('م. محمود خير', 'م. محمود خير'), ('م. محمد شوقي', 'م. محمد شوقي'), ('م. أحمد يونس', 'م. أحمد يونس'), ('م. شحاته عبدالعزيز', 'م. شحاته عبدالعزيز')], max_length=30, null=True),
        ),
    ]
