# Generated by Django 3.2 on 2023-01-09 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0011_alter_follow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_dvr',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='follow.building'),
        ),
    ]
