# Generated by Django 3.2 on 2023-01-11 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0013_dvr_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dvr_info',
            old_name='dvr_cam_ports',
            new_name='dvr_cam_place',
        ),
    ]
