# Generated by Django 3.2 on 2023-01-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('follow', '0014_rename_dvr_cam_ports_dvr_info_dvr_cam_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dvr_info',
            name='drv_mic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='عدد المايك'),
        ),
        migrations.AlterField(
            model_name='dvr_info',
            name='dvr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='follow.add_dvr'),
        ),
        migrations.AlterField(
            model_name='dvr_info',
            name='dvr_cam_connect',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='عدد الكاميرات'),
        ),
        migrations.AlterField(
            model_name='dvr_info',
            name='dvr_cam_place',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='مكانه دور ومبني'),
        ),
        migrations.AlterField(
            model_name='dvr_info',
            name='dvr_ip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='dvr_info',
            name='dvr_notes',
            field=models.TextField(blank=True, max_length=30, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='dvr_info',
            name='dvr_ports',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='عدد المخارج'),
        ),
        migrations.AlterField(
            model_name='dvr_info',
            name='dvr_typ',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='نوعه'),
        ),
    ]
